#!/bin/bash
echo "Commands to run on remote server:"
echo ""
echo "cd eastern.yushi-marketing.com"
echo "php artisan route:clear"
echo "php artisan cache:clear"
echo "php artisan config:clear"
echo "php artisan view:clear"
echo ""
echo "These commands will clear all Laravel caches including route cache."
